/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-06-22 04:26:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.advanced;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.eclipse.help.internal.webapp.data.*;

public final class views_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/advanced/header.jsp", Long.valueOf(1252574902000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.eclipse.help.internal.webapp.data");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 
request.setCharacterEncoding("UTF-8");
boolean isRTL = UrlUtil.isRTL(request, response);
String  direction = isRTL?"rtl":"ltr";
if (new RequestData(application,request, response).isMozilla()) {

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n");
 
} else {

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");

}

      out.write("<!------------------------------------------------------------------------------\n");
      out.write(" ! Copyright (c) 2000, 2004 IBM Corporation and others.\n");
      out.write(" ! All rights reserved. This program and the accompanying materials \n");
      out.write(" ! are made available under the terms of the Eclipse Public License v1.0\n");
      out.write(" ! which accompanies this distribution, and is available at\n");
      out.write(" ! http://www.eclipse.org/legal/epl-v10.html\n");
      out.write(" ! \n");
      out.write(" ! Contributors:\n");
      out.write(" !     IBM Corporation - initial API and implementation\n");
      out.write(" ------------------------------------------------------------------------------->");
      out.write('\n');
      out.write('\n');
 
	LayoutData data = new LayoutData(application,request, response);
	WebappPreferences prefs = data.getPrefs();
	View[] views = data.getViews();

      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\n");
      out.write("<title>");
      out.print(ServletResources.getString("Views", request));
      out.write("</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/* need this one for Mozilla */\n");
      out.write("HTML { \n");
      out.write("\twidth:100%;\n");
      out.write("\theight:100%;\n");
      out.write("\tmargin:0px;\n");
      out.write("\tpadding:0px;\n");
      out.write("\tborder:0px;\n");
      out.write(" }\n");
      out.write("\n");
      out.write("BODY {\n");
      out.write("\tmargin:0px;\n");
      out.write("\tpadding:0px;\n");
      out.write("\t/* Mozilla does not like width:100%, so we set height only */\n");
      out.write("\theight:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("IFRAME {\n");
      out.write("\twidth:100%;\n");
      out.write("\theight:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hidden {\n");
      out.write("\tvisibility:hidden;\n");
      out.write("\twidth:0;\n");
      out.write("\theight:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".visible {\n");
      out.write("\tvisibility:visible;\n");
      out.write("\twidth:100%;\n");
      out.write("\theight:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script language=\"Javascript\">\n");
      out.write("\n");
      out.write("var lastView = \"\";\n");
      out.write("/**\n");
      out.write(" * Switches to specified view\n");
      out.write(" */\n");
      out.write("function showView(view)\n");
      out.write("{ \t\n");
      out.write("\tif (view == lastView) \n");
      out.write("\t\treturn;\n");
      out.write("\t\t\n");
      out.write("\tlastView = view;\n");
      out.write("       \t\n");
      out.write("\t// show appropriate frame\n");
      out.write(" \tvar iframes = parent.ViewsFrame.document.body.getElementsByTagName(\"IFRAME\");\n");
      out.write(" \tfor (var i=0; i<iframes.length; i++)\n");
      out.write(" \t{\t\t\t\n");
      out.write("  \t\tif (iframes[i].id != view){\n");
      out.write("   \t\t\tiframes[i].className = \"hidden\";\n");
      out.write("   \t\t\tiframes[i].style.visibility=\"hidden\";\n");
      out.write("  \t\t}else{\n");
      out.write("   \t\t\tiframes[i].className = \"visible\";\n");
      out.write("   \t\t\tiframes[i].style.visibility=\"visible\";\n");
      out.write("   \t\t}\n");
      out.write(" \t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("var activityFiltering = ");
      out.print((new ActivitiesData(application, request, response)).isActivityFiltering()?"true":"false");
      out.write(";\n");
      out.write("var displayShowAllConfirmation = ");
      out.print(prefs.isDontConfirmShowAll()?"false":"true");
      out.write(";\n");
      out.write("var regExp=/&(showAll|synch)=(on|off|yes|no)/gi;\n");
      out.write("function toggleShowAll(){\n");
      out.write("\tif(activityFiltering){\n");
      out.write("\t\tif( displayShowAllConfirmation ){\n");
      out.write("\t\t\tconfirmShowAll();\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tshowAll();\n");
      out.write("\t\t}\n");
      out.write("\t} else {\n");
      out.write("\t\tdontShowAll();\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function dontAskAgain(){\n");
      out.write("\tdisplayShowAllConfirmation = false;\n");
      out.write("}\n");
      out.write("function showAll(){\n");
      out.write("\tvar displayConfirmParam;\n");
      out.write("\tif(displayShowAllConfirmation){\n");
      out.write("\t\tdisplayConfirmParam=\"\";\n");
      out.write("\t}else{\n");
      out.write("\t\tdisplayConfirmParam=\"&showconfirm=false\";\n");
      out.write("\t}\n");
      out.write("\tactivityFiltering=false;\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.toc.tocToolbarFrame.setButtonState(\"show_all\", true);\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.search.searchToolbarFrame.setButtonState(\"show_all\", true);\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.toc.tocViewFrame.location.replace(window.frames.toc.tocViewFrame.location.href.replace(regExp, \"\")+\"&showAll=on\"+displayConfirmParam);\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.search.searchViewFrame.location.replace(window.frames.search.searchViewFrame.location.href.replace(regExp, \"\")+\"&showAll=on\");\n");
      out.write("\t}catch(ex) {}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function dontShowAll(){\n");
      out.write("\tactivityFiltering=true;\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.toc.tocToolbarFrame.setButtonState(\"show_all\", false);\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.search.searchToolbarFrame.setButtonState(\"show_all\", false);\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.toc.tocViewFrame.location.replace(window.frames.toc.tocViewFrame.location.href.replace(regExp, \"\")+\"&showAll=off\");\n");
      out.write("\t}catch(ex) {}\n");
      out.write("\ttry{\n");
      out.write("\t\twindow.frames.search.searchViewFrame.location.replace(window.frames.search.searchViewFrame.location.href.replace(regExp, \"\")+\"&showAll=off\");\n");
      out.write("\t}catch(ex) {}\n");
      out.write("}\n");
      out.write("\n");
      out.write("var confirmShowAllDialog;\n");
      out.write("var w = 470;\n");
      out.write("var h = 300;\n");
      out.write("\n");
      out.write("function confirmShowAll()\n");
      out.write("{\n");

if (data.isIE()){

      out.write("\n");
      out.write("\tvar l = top.screenLeft + (top.document.body.clientWidth - w) / 2;\n");
      out.write("\tvar t = top.screenTop + (top.document.body.clientHeight - h) / 2;\n");

} else {

      out.write("\n");
      out.write("\tvar l = top.screenX + (top.innerWidth - w) / 2;\n");
      out.write("\tvar t = top.screenY + (top.innerHeight - h) / 2;\n");

}

      out.write("\n");
      out.write("\t// move the dialog just a bit higher than the middle\n");
      out.write("\tif (t-50 > 0) t = t-50;\n");
      out.write("\t\n");
      out.write("\twindow.location=\"javascript://needModal\";\n");
      out.write("\tconfirmShowAllDialog = window.open(\"confirmShowAll.jsp\", \"confirmShowAllDialog\", \"resizeable=no,height=\"+h+\",width=\"+w+\",left=\"+l+\",top=\"+t );\n");
      out.write("\tconfirmShowAllDialog.focus(); \n");
      out.write("}\n");
      out.write("\n");
      out.write("function closeConfirmShowAllDialog(){\n");
      out.write("\ttry {\n");
      out.write("\t\tif (confirmShowAllDialog){\n");
      out.write("\t\t\tconfirmShowAllDialog.close();\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tcatch(e) {}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("   \n");
      out.write("<body dir=\"");
      out.print(direction);
      out.write("\" tabIndex=\"-1\" onunload=\"closeConfirmShowAllDialog()\">\n");

	for (int i=0; i<views.length; i++) 
	{
		// normally we would hide the views first, but mozilla needs all iframes to be visible to load 
		// other frames
		String className =  data.getVisibleView().equals(views[i].getName()) || data.isMozilla() ? "visible" : "hidden";

      out.write("\n");
      out.write(" \t<iframe frameborder=\"0\" \n");
      out.write(" \t\t    class=\"");
      out.print(className);
      out.write("\"  \n");
      out.write(" \t\t    name=\"");
      out.print(views[i].getName());
      out.write("\"\n");
      out.write(" \t\t    title=\"");
      out.print(ServletResources.getString("ignore", views[i].getName(), request));
      out.write("\"\n");
      out.write(" \t\t    id=\"");
      out.print(views[i].getName());
      out.write("\" \n");
      out.write(" \t\t    src='");
      out.print("view.jsp?view="+views[i].getName()+(request.getQueryString()==null?"":("&"+request.getQueryString())));
      out.write("'>\n");
      out.write(" \t</iframe> \n");

	}

      out.write("\t\n");
      out.write("\n");
      out.write(" <iframe frameborder=\"0\" style=\"visibility:hidden\" tabindex=\"-1\" name=\"temp\" id=\"temp\" title=\"");
      out.print(ServletResources.getString("ignore", "temp", request));
      out.write("\"></iframe>\n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
